-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 12:46:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db.triplan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db.triplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db.triplan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db.triplan` ;

-- -----------------------------------------------------
-- Table `db.triplan`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db.triplan`.`city` (
  `idcity` INT(11) NOT NULL,
  `name_city` VARCHAR(45) NULL DEFAULT NULL,
  `stato` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db.triplan`.`tab_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db.triplan`.`tab_user` (
  `userId` INT(11) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `usertype` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db.triplan`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db.triplan`.`booking` (
  `idbooking` INT(11) NOT NULL,
  `book_username` VARCHAR(45) NULL DEFAULT NULL,
  `book_city` VARCHAR(45) NULL DEFAULT NULL,
  `date_departeur` DATE NULL DEFAULT NULL,
  `date_arrival` DATE NULL DEFAULT NULL,
  `city_idcity` INT(11) NOT NULL,
  `tab_user_userId` INT(11) NOT NULL,
  PRIMARY KEY (`idbooking`),
  INDEX `fk_booking_city1_idx` (`city_idcity` ASC) VISIBLE,
  INDEX `fk_booking_tab_user1_idx` (`tab_user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_booking_city1`
    FOREIGN KEY (`city_idcity`)
    REFERENCES `db.triplan`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_tab_user1`
    FOREIGN KEY (`tab_user_userId`)
    REFERENCES `db.triplan`.`tab_user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db.triplan`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db.triplan`.`places` (
  `idplaces` INT(11) NOT NULL,
  `name_places` VARCHAR(45) NULL DEFAULT NULL,
  `city_places` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `city_idcity` INT(11) NOT NULL,
  PRIMARY KEY (`idplaces`),
  INDEX `fk_places_city1_idx` (`city_idcity` ASC) VISIBLE,
  CONSTRAINT `fk_places_city1`
    FOREIGN KEY (`city_idcity`)
    REFERENCES `db.triplan`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db.triplan`.`city`
-- -----------------------------------------------------
START TRANSACTION;
USE `db.triplan`;
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (1, 'roma', 'italia');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (2, 'firenze', 'italia');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (3, 'milano', 'italia');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (4, 'madrid', 'spagna');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (5, 'barcellona', 'spagna');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (6, 'berlino', 'germania');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (7, 'monaco', 'germania');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (8, 'new york', 'usa');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (9, 'san francisco', 'usa');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (10, 'washington', 'usa');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (11, 'parigi', 'francia');
INSERT INTO `db.triplan`.`city` (`idcity`, `name_city`, `stato`) VALUES (12, 'nizza', 'francia');

COMMIT;

