SET FOREIGN_KEY_CHECKS = 0; 
TRUNCATE table places; 
SET FOREIGN_KEY_CHECKS = 1;



INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (1,'roma',41.5407,12.2724,'san pietro','religione',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (2,'roma',41.5325,12.2931,'colosseo','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (3,'roma',41.5355,12.2838,'pantheon','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (4,'firenze',43.4623,11.1522,'santa maria del fiore','religione',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (5,'firenze',43.4604,11.1516,'uffizi','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (6,'firenze',43.4605,11.1512,'ponte vecchio','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (7,'parigi',48.513,2.174,'tour eiffel','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (8,'barcellona',41.2412,2.1027,'sagrada famiglia','religione',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (9,'madrid',40.2449,3.413,'museo del prado','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (10,'barcellona',41.233,2.0944,'ramblas','divertimento',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (11,'barcellona',41.2251,2.0721,'camp nou','divertimento',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (12,'madrid',40.2711,3.4118,'santiago bernabeu','divertimento',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (13,'roma',41.5403,12.29,'fontana di trevi','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (14,'roma',41.542,12.2855,'piazza di spagna','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (15,'roma',41.5357,12.2824,'piazza navona','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (16,'roma',41.5302,12.2915,'circo massimo','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (17,'roma',41.5344,12.2858,'piazza venezia','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (18,'roma',41.5439,12.2836,'piazza del popolo','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (19,'roma',41.5244,12.2932,'terme di caracalla','cultura',1);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (20,'firenze',43.4555,11.1459,'palazzo pitti','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (21,'firenze',43.461,11.152,'piazza della signoria','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (22,'firenze',43.4608,11.1541,'basilica di santa croce','religione',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (23,'firenze',43.4623,11.1519,'piazza del duomo','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (24,'firenze',43.4631,11.1521,'palazzo medici','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (25,'firenze',43.4544,11.1444,'giardino di boboli','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (26,'firenze',43.4609,11.152,'loggia della signoria','cultura',2);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (27,'milano',45.2751,9.113,'duomo','religione',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (28,'milano',45.2806,9.1122,'teatro la scala','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (29,'milano',45.2813,9.1045,'castello sforzesco','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (30,'milano',45.2757,9.1014,'santa maria delle grazie','religione',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (31,'milano',45.2819,9.1038,'parco sempione','divertimento',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (32,'milano',45.2805,9.1142,'via montenapoleone','divertimento',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (33,'milano',45.2819,9.1117,'pinacoteca di brera','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (34,'milano',45.2748,9.1108,'biblioteca ambrosiana','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (35,'milano',45.2755,9.111,'piazza cordusio','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (36,'milano',45.2759,9.1127,'piazza san fedele','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (37,'milano',45.2822,9.12,'galleria arte moderna','cultura',3);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (38,'madrid',40.2504,3.4251,'palazzo reale','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (39,'madrid',40.2456,3.4227,'plaza mayor','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (40,'madrid',40.2455,3.4103,'parco del retiro','divertimento',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (41,'madrid',40.2501,3.4213,'puerta del sol','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (42,'madrid',40.2513,3.4214,'gran via','divertimento',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (43,'madrid',40.2505,3.4237,'teatro real','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (44,'madrid',40.2429,3.4138,'museo reina sofia','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (45,'madrid',40.2512,3.412,'puerta de alcala','cultura',4);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (46,'barcellona',41.5442,2.091,'parco guell','cultura',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (47,'barcellona',41.2302,2.1033,'cattedrale barcellona','religione',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (48,'barcellona',41.233,2.0953,'casa batlo','cultura',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (49,'barcellona',41.2343,2.0942,'casa mila','cultura',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (50,'barcellona',41.2236,2.1102,'acquario','divertimento',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (51,'barcellona',41.2317,2.111,'parco della cittadella','divertimento',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (52,'barcellona',41.2302,2.1055,'santa maria del mar','religione',5);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (53,'parigi',48.5313,2.2038,'sacro cuore','religione',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (54,'parigi',48.5138,2.2015,'louvre','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (55,'parigi',48.5226,2.1742,'arco di trionfo','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (56,'parigi',48.511,2.2057,'notre dame','religione',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (57,'parigi',48.4817,2.0712,'reggia di versailles','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (58,'parigi',48.5211,2.1827,'campi elisi','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (59,'parigi',48.5311,2.2038,'montmartre','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (60,'parigi',48.5149,2.21,'saint denis','religione',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (61,'parigi',48.5156,2.1915,'piazza della concordia','cultura',11);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (62,'nizza',43.4052,6.1355,'passeggiata degli inglesi','divertimento',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (63,'nizza',43.4149,7.1632,'cattedrale di nizza','religione',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (64,'nizza',43.4212,7.1556,'notre dame di nizza','religione',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (65,'nizza',43.4144,7.1621,'opera','cultura',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (68,'nizza',43.431,7.1633,'museo matisse','cultura',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (69,'nizza',43.4115,7.1239,'giardino botanico','divertimento',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (70,'nizza',43.4142,7.1455,'museo delle belle arti','cultura',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (71,'nizza',43.4213,7.1513,'chiesa di san nicola','religione',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (72,'nizza',43.4234,7.1612,'museo marc chagall','cultura',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (73,'nizza',43.4042,7.1157,'palazzo nikaia','cultura',12);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (74,'berlino',52.3206,13.2324,'muro di berlino','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (75,'berlino',52.2358,13.0254,'porta di brandeburgo','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (76,'berlino',52.3107,13.2233,'palazzo del reichstag','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (77,'berlino',52.3108,13.2404,'duomo di berlino','religione',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (78,'berlino',52.3052,13.21,'colonna della vittoria','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (79,'berlino',52.3115,13.1744,'castello di charlottenburg','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (80,'berlino',52.301,13.2248,'fuhrerbunker','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (81,'berlino',52.311,13.2356,'altes museo','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (82,'berlino',52.3119,13.2447,'alexanderplatz','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (83,'berlino',52.3027,13.2324,'checkpoint charlie','cultura',6);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (84,'monaco',48.1307,11.3728,'allianz arena','divertimento',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (85,'monaco',48.1036,11.3335,'torre bmw','divertimento',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (86,'monaco',47.3327,10.4458,'castello di neuschwanstein','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (87,'monaco',48.0813,11.3433,'marienplatz','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (88,'monaco',48.0819,11.3424,'frauenkirche','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (89,'monaco',48.0929,11.3011,'castello nymphenburg','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (90,'monaco',48.0815,11.3447,'hofbrauhaus','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (91,'monaco',48.0847,11.3357,'gliptoteca','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (92,'monaco',48.1023,11.3246,'olympiastadion','divertimento',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (93,'monaco',48.0811,11.354,'maximilianeum','cultura',7);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (94,'new york',40.4121,74.0242,'liberty statue','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (95,'new york',40.4658,73.5755,'central park','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (96,'new york',40.4531,73.5903,'times square','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (97,'new york',40.4453,73.5909,'empire state building','divertimento',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (98,'new york',40.4221,73.5951,'ponte di brooklyn ','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (99,'new york',40.4227,74.0035,'wall street','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (100,'new york',40.4256,73.5949,'china town','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (101,'new york',40.4531,73.5842,'rockefeller center','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (102,'new york',40.4241,74.0048,'museo 11 settembre','divertimento',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (103,'new york',40.3431,73.5812,'coney island','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (104,'new york',40.4309,73.595,'little italy','cultura',8);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (105,'san francisco',37.4911,122.2843,'golden gate bridge','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (106,'san francisco',37.4936,122.2522,'alcatraz','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (107,'san francisco',37.4803,122.2535,'lombard street','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (108,'san francisco',37.4639,122.2559,'alamo square','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (109,'san francisco',37.4742,122.241,'transamerica pyramid','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (110,'san francisco',37.4609,122.291,'golden gate park','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (111,'san francisco',37.4509,122.265,'twin peaks','divertimento',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (112,'san francisco',37.4539,122.2605,'castro street','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (113,'san francisco',37.4642,122.2321,'oracle park','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (114,'san francisco',37.4809,122.2421,'coit tower','cultura',9);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (115,'washington',38.5351,77.0211,'white house','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (116,'washington',38.5323,77.0032,'campidoglio','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (117,'washington',38.5322,77.0206,'monumento a washington','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (118,'washington',38.5321,77.03,'lincoln memorial','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (119,'washington',38.5322,77.0122,'national mall','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (120,'washington',38.5252,77.0212,'jefferson memorial ','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (121,'washington',38.5435,77.0238,'dupont circle','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (122,'washington',38.5347,77.0133,'teatro ford','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (123,'washington',38.5328,77.0111,'national gallery of art','cultura',10);
INSERT INTO `triplanrest`.`places` (`id_places`,`cityplaces`,`latitude`,`longitude`,`nameplaces`,`type`,`id_city`) VALUES (124,'washington',38.5345,77.0321,'kennedy center','cultura',10);
commit;